permalink: /post/:year/:month/:day/:title.html
paginate: 12
paginate_path: "static/:num"
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  auto_id_prefix: 'toc-'

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1